[package]
name = "doug"
version = "0.1.0"
authors = ["Cole Poirier <colepoirier@gmail.com>"]
edition = "2021"


[dependencies]
# Local workspace dependencies
layout21raw = { path = "../Layout21/layout21raw", features = ["proto"] }
gds21 = { path = "../Layout21/gds21" }
# layout21protos = { path = "../Layout21/layout21protos" }
# layout21utils = { path = "../Layout21/layout21utils" }
# Crates.io 
num-traits = "0.2.14"
anyhow = "1.0.43"
bevy = { version = "0.5.0", features = ["dynamic"] }
derive_more = "0.99.16"
bevy_prototype_lyon = "0.3.1"
prost = "0.9.0"
lyon_path = "0.17.7"
