[package]
name = "doug"
version = "0.1.0"
authors = ["Cole Poirier <colepoirier@gmail.com>"]
edition = "2021"


[dependencies]
# Local workspace dependencies
layout21 = { git = "https://github.com/dan-fritchman/Layout21.git" }
# bevy_prototype_lyon = { path = "../bevy_prototype_lyon" }
bevy_prototype_lyon = "0.3.1"
# bevy_config_cam = { path = "../bevy_config_cam" }
# bevy_config_cam = "0.1.3"
# bevy-inspector-egui = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", branch = "bevy-main" }
# bevy-inspector-egui = { path = "../bevy-inspector-egui" }
bevy-inspector-egui = { version = "0.6.1", features = ["rapier2d"] }

# Crates.io 
num-traits = "0.2.14"
anyhow = "1.0.51"
derive_more = "0.99.17"
prost = "0.9.0"
itermore = "0.1.0"
bevy_rapier2d = "0.11.0"

[dependencies.bevy]
version = "0.5.0"
default-features = false
features = ["bevy_wgpu", "bevy_winit", "render", "png", "hdr", "x11"]

# [patch.crates-io]
# # override it with bevy from git
# bevy = { git = "https://github.com/bevyengine/bevy" }

# [profile.release]
# opt-level = 3
# codegen-units = 1
# lto = true

# [profile.test]
# opt-level = 3
# debug = 2
