[package]
name = "doug"
version = "0.1.0"
authors = ["Cole Poirier <colepoirier@gmail.com>"]
edition = "2021"

[dependencies]
num-traits = "0.2.14"
anyhow = "1.0.52"
derive_more = "0.99.17"
prost = "0.9.0"
bevy_prototype_lyon = "0.3.1"
layout21 = { git = "https://github.com/dan-fritchman/Layout21.git" }

[dependencies.bevy]
version = "0.5.0"
default-features = false
features = ["bevy_wgpu", "bevy_winit", "render", "png", "hdr", "x11"]
